pyuic5 ./ui_transaction_dlg.ui > ./ui_transaction_dlg.py
pyuic5 ./ui_proposals.ui > ./ui_proposals.py
pyuic5 ./ui_main_dlg.ui > ./ui_main_dlg.py
pyuic5 ./ui_doc_dlg.ui > ./ui_doc_dlg.py
pyuic5 ./ui_hw_pass_dlg.ui > ./ui_hw_pass_dlg.py
pyuic5 ./ui_wallet_dlg_options1.ui > ./ui_wallet_dlg_options1.py
pyuic5 ./ui_conn_rpc_wdg.ui > ./ui_conn_rpc_wdg.py
pyuic5 ./ui_thread_fun_dlg.ui > ./ui_thread_fun_dlg.py
pyuic5 ./ui_wdg_wallet_txes_filter.ui > ./ui_wdg_wallet_txes_filter.py
pyuic5 ./ui_cmd_console_dlg.ui > ./ui_cmd_console_dlg.py
pyuic5 ./ui_message_dlg.ui > ./ui_message_dlg.py
pyuic5 ./ui_hw_pin_dlg.ui > ./ui_hw_pin_dlg.py
pyuic5 ./ui_hw_setup_dlg.ui > ./ui_hw_setup_dlg.py
pyuic5 ./ui_conn_ssh_wdg.ui > ./ui_conn_ssh_wdg.py
pyuic5 ./ui_masternode_details.ui > ./ui_masternode_details.py
pyuic5 ./ui_config_dlg.ui > ./ui_config_dlg.py
pyuic5 ./ui_about_dlg.ui > ./ui_about_dlg.py
pyuic5 ./ui_wallet_dlg.ui > ./ui_wallet_dlg.py
pyuic5 ./ui_find_coll_tx_dlg.ui > ./ui_find_coll_tx_dlg.py
pyuic5 ./ui_hw_word_dlg.ui > ./ui_hw_word_dlg.py
pyuic5 ./ui_initialize_hw_dlg.ui > ./ui_initialize_hw_dlg.py
pyuic5 ./ui_sign_message_dlg.ui > ./ui_sign_message_dlg.py
pyuic5 ./ui_columns_cfg_dlg.ui > ./ui_columns_cfg_dlg.py
pyuic5 ./ui_reg_masternode_dlg.ui > ./ui_reg_masternode_dlg.py